---
env:
  node: true
  es6: true
  commonjs: true
  jest/globals: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: 'module'
  project: tsconfig.json
plugins:
  - jest
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:jest/recommended
  - prettier
  - prettier/@typescript-eslint
rules:
  '@typescript-eslint/naming-convention':
    - error
    - selector: default
      format:
        - camelCase
        - PascalCase
        # - snake_case
        - UPPER_CASE
        # ID とかを許さない variation ( Id なら可 )
        # - strictCamelCase
        # - StrictPascalCase
      leadingUnderscore: allow
